version: "3"
services:
  web:
    build:
      context: .
      args:
        NODE_ENV: development
      ports:
        - "5000:3000"
    command: npm run start
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
  build:
    build:
      context: .
      args:
        NODE_ENV: production
      target: production
